Enable parallel computing for find_center_vo, allow 2D sinogram input…
tomopy/tomopy pull request #523
Opened 2020-09-30 22:07 UTC by nghia-vo

…, fix bug caused by downsampling

2020-10-01 23:20 UTC, carterbox commented on source/tomopy/recon/rotation.py
> +                   ratio=0.5, drop=20, parallel=True):
Please match the rest of the library by using `ncore, nchunk` parameters with default value of `None`. The `distribute_jobs` function automatically chooses values for these parameters.

https://github.com/tomopy/tomopy/blob/1047c0b59de3bf5026209b670ba4b1ebd03ba9f9/source/tomopy/prep/stripe.py#L88-L90

2020-10-01 23:26 UTC, carterbox requested changes
Hi @nghia-vo. thanks for the PR. In addition to the comments below, could you please separate the changes for the bug fix and the "allowing of 2D inputs" into their own commits? It will help me understand which changes go with which objective.

2020-10-01 23:26 UTC, carterbox commented on source/tomopy/recon/rotation.py
> +                   ratio=0.5, drop=20, parallel=True):
Please match the rest of the library by using `ncore, nchunk` parameters with default value of `None`. The `distribute_jobs` function automatically chooses values for these parameters.

https://github.com/tomopy/tomopy/blob/1047c0b59de3bf5026209b670ba4b1ebd03ba9f9/source/tomopy/prep/stripe.py#L88-L90

2020-10-01 23:26 UTC, carterbox commented on source/tomopy/recon/rotation.py
> +    else:
For example, instead of setting `parallel=False`, users can set `ncore=1` and `nchunk=1`.

2020-10-12 21:38 UTC, nghia-vo commented
Update and separate commits as requested. However nchunk must be set to 1 for the function to work.

2020-10-13 18:26 UTC, carterbox commented
I think it's fine if `nchunk=1` is hardcoded in this case. I also removed the `if ncore !=1 else` statement. The number of cores should not affect the result of `distribute_jobs()`.

2020-10-15 11:05 UTC, nghia-vo commented
I've checked the update. Good to go.

2020-10-15 15:58 UTC, merged