Add dimension check to gridrec
tomopy/tomopy pull request #605
Opened 2023-02-21 21:19 UTC by samtygier-stfc

Check that theta array matches the `dt` that is being passed to the c function.

Closes #604

2023-02-21 21:23 UTC, samtygier-stfc commented
Should I add the same for the other c wrappers?

2023-02-21 21:32 UTC, carterbox requested changes
Thank you for opening this PR to squash this bug.

This check should be located in `tomopy.recon.algorithm.recon()` near the top of the function. Add something like:

```python
    if tomo.shape[1] != len(theta):
        msg = 'There must be one angle for every projection.'
        raise ValueError(msg)
```

2023-02-21 21:39 UTC, samtygier-stfc commented
My reason for putting it near the c call was to make it certain when considering the c code that the arrays and sizes passed in are compatible.

But I am happy to move it into `recon()` if you prefer.

2023-02-21 23:19 UTC, carterbox commented
I prefer checking in `recon()` because it provides the best coverage, and the util.extern module is non-public, so it shouldn't be called directly.

2023-02-22 09:00 UTC, samtygier-stfc commented
Ok, moved it into `recon()`. I think we can assume here that it is 3D, otherwise `_get_algorithm_kwargs` gives an error.

I'd like to also add a check for `center`.

2023-02-27 21:44 UTC, carterbox requested changes

2023-03-02 22:54 UTC, samtygier-stfc commented on source/tomopy/recon/algorithm.py
> +
It is needed if center is and array or list with a size different from 1, then its shape is preserved. So in:

```
obj = tomopy.shepp3d()
ang = tomopy.angles(180)
c = [5,5,5]
rec = tomopy.recon(sim, ang, center=c, algorithm="gridrec")
```
the wrong sized array is passed to `c_gridrec` and the c function uses values beyond its end.

2023-03-03 20:30 UTC, carterbox approved these changes

2023-03-03 20:31 UTC, carterbox commented
Thanks for your contribution!

2023-03-03 20:41 UTC, merged