Inpainting 2D/3D algorithm to tackle missing data
tomopy/tomopy pull request #631
Opened 2023-10-30 16:37 UTC by dkazanc

In this PR a new [inpainting algorithm](https://docs.opencv.org/3.4/df/d3d/tutorial_py_inpainting.html) is presented. This is a morphological iterative implementation where the contracting boundary of the missing data region evolves under the set of simple rules. Because the algorithm is not based on any PDEs (e.g. [Active Contours](https://en.wikipedia.org/wiki/Active_contour_model)) it is also very fast in convergence and usually "just works" for the set of the same default parameters. 
I guess the main drawback of this is that it doesn't necessarily preserve the direction of features when perform smoothing. However the direction of features in sinograms can be very hard to estimate and usually unknown for complex objects and scanning geometries. Having said this, for relatively small areas of inpainting, the direction of features can be relatively preserved.

There are 3 algorithms presented in total: 
1. Uses a simple **mean** of the neighbourhood to inpaint the missing value
2. Uses a **median** value
3. Uses a **random** value

The third (random) is generally recommended to use as this algorithm reduces the amount of intensity overspill that can be present with mean or also median methods.

This algorithm can be used with the [stripes detection](https://tomopy.readthedocs.io/en/stable/api/tomopy.prep.stripe.html#tomopy.prep.stripe.stripes_detect3d) to remove strong stripes as here:
![Screenshot from 2023-10-30 15-16-17](https://github.com/tomopy/tomopy/assets/6651977/cdb7c2ff-42b6-4fb6-8f7d-ca062d3e2af8)
OR
in application to reconstructed images or even natural images (though expect some oversmoothing)
![Screenshot from 2023-10-30 16-03-18](https://github.com/tomopy/tomopy/assets/6651977/2cf30d0d-5ee3-41ea-9724-8f6e80c2e227)

The code is in C, tests added. 
Thanks! 
P.S. The paper where this algorithm is featured is in revision atm, so I should be able to add some references later.

2023-10-30 16:37 UTC, pep8speaks commented
Hello @dkazanc! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`source/tomopy/misc/corr.py`](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py):

> [Line 972:1](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L972): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 972:25](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L972): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 980:81](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L980): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (118 > 80 characters)
> [Line 989:52](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L989): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 994:81](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L994): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 80 characters)
> [Line 994:84](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L994): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 997:46](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L997): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 999:81](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L999): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 80 characters)
> [Line 1001:81](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L1001): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 80 characters)
> [Line 1001:91](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L1001): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1002:43](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L1002): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1016:1](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L1016): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1030:81](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L1030): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (129 > 80 characters)
> [Line 1034:81](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L1034): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 80 characters)
> [Line 1035:1](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L1035): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1042:1](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L1042): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1045:1](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L1045): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1081:29](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L1081): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 1082:29](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L1082): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 1083:29](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L1083): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 1084:29](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L1084): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 1085:29](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L1085): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 1086:29](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L1086): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 1087:29](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/misc/corr.py#L1087): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

* In the file [`source/tomopy/util/extern/misc.py`](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/util/extern/misc.py):

> [Line 189:1](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/source/tomopy/util/extern/misc.py#L189): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

* In the file [`test/test_tomopy/test_misc/test_corr.py`](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/test/test_tomopy/test_misc/test_corr.py):

> [Line 144:1](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/test/test_tomopy/test_misc/test_corr.py#L144): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 147:29](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/test/test_tomopy/test_misc/test_corr.py#L147): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 148:29](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/test/test_tomopy/test_misc/test_corr.py#L148): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 150:25](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/test/test_tomopy/test_misc/test_corr.py#L150): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 151:81](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/test/test_tomopy/test_misc/test_corr.py#L151): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (106 > 80 characters)
> [Line 152:81](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/test/test_tomopy/test_misc/test_corr.py#L152): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 80 characters)
> [Line 153:81](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/test/test_tomopy/test_misc/test_corr.py#L153): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 80 characters)
> [Line 154:81](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/test/test_tomopy/test_misc/test_corr.py#L154): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 80 characters)
> [Line 155:81](https://github.com/tomopy/tomopy/blob/d3acc5b7f1475932b2dfa000ff4dd28116e89b9e/test/test_tomopy/test_misc/test_corr.py#L155): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 80 characters)
> [Line 157:81](https://github.com/tomopy/to [...]

2023-11-23 10:50 UTC, dkazanc commented
just preparing few slides here and did this experiment by cutting off the missing wedge, so it helps to minimise some artefacts (a bit)
![image](https://github.com/tomopy/tomopy/assets/6651977/7da4107a-2189-4056-bfa6-f0e76d02067c)

2023-11-27 20:46 UTC, carterbox requested changes

2023-11-27 20:53 UTC, carterbox commented
It's also unclear to me from the documentation what the difference between 2D and 3D. There are three dimensions in the projection data: vertical, horizontal, and angle. Is 2D (vertical, horizontal) or (horizontal, angle) or (vertical, angle)?

2023-12-12 12:51 UTC, dkazanc commented on source/libtomo/misc/inpainter.c
> +    if (ncores > 0)
true, I guess it is always positive, so the condition can be removed?

2023-12-12 23:12 UTC, carterbox commented on source/libtomo/misc/inpainter.c
> +    if (ncores > 0)
What happens if `omp_set_num_threads(0)` or `omp_set_num_threads(-1)`? Does that cause a problem?

2023-12-12 23:34 UTC, carterbox requested changes
Your explanation that inpainting should be done on the sinogram instead of in the projection space to get better results makes sense. However, the docs don't explicitly explain how to do that.

For example, if I have 3D data, but select 2D inpainting, over which two dimensions will the inpainting operate? 0 and 1? 1 and 2? 0 and 2? (I assume for 3D inpainting on 3D data, axes order doesn't matter.)

Our reconstruction algorithm allows two different orderings of 3D data:

> Determins whether data is a stack of sinograms (True, y-axis first axis) or a stack of radiographs (False, theta first axis).

so I think that TomoPy does not have a canonical data ordering.

Please add to the docstrings
1. the explanation that inpainting sinograms works better
2. which two axes the 2D method uses for 3D input

2023-12-12 23:34 UTC, carterbox commented on test/test_tomopy/test_misc/test_corr.py
> +        lena_image = read_file("lena.npy")
Please use the `tomopy.misc.phantom.peppers()` or one of the others instead of adding a new test image to the repo.

2024-01-10 15:29 UTC, dkazanc commented
Thanks, will do some correction as requested.  
Meanwhile I'm trying to build the library in a new `linux-cuda.yaml` environment. When I run `cmake --build` I get:

```
In file included from /*/tomopy/source/libtomo/accel/constants.hh:47,
                 from /*/tomopy/source/libtomo/accel/common.hh:42,
                 from /*/tomopy/source/libtomo/accel/cxx/sirt.cc:40:
/*/tomopy/source/libtomo/accel/macros.hh:98:10: fatal error: PTL/AutoLock.hh: No such file or directory
   98 | #include "PTL/AutoLock.hh"
```
Any ideas? thanks

2024-01-10 16:24 UTC, carterbox commented
You probably need to reinitialize the PTL git submodule. [CMake is supposed to do that automatically ](https://github.com/tomopy/tomopy/blob/fa3a35dd5e029ebf43932a45e769dbb3eca5a2b0/source/CMakeLists.txt#L23C6-L23C6) for you though.
```
git submodule update --init --recursive
```

2024-01-11 09:24 UTC, dkazanc commented
> You probably need to reinitialize the PTL git submodule. [CMake is supposed to do that automatically ](https://github.com/tomopy/tomopy/blob/fa3a35dd5e029ebf43932a45e769dbb3eca5a2b0/source/CMakeLists.txt#L23C6-L23C6) for you though.
> 
> ```
> git submodule update --init --recursive
> ```
Thanks, that helped. Yes, strangely Cmake skipped it for some reason.

2024-01-11 13:27 UTC, dkazanc commented on source/libtomo/misc/inpainter.c
> +    if (ncores > 0)
Don't know about this TBH. I guess it won't like it, hence the condition. Do you want me to test it?

2024-01-12 17:19 UTC, carterbox commented on source/libtomo/misc/inpainter.c
> +    if (ncores > 0)
I guess my real question, is "What is the expected behavior when ncores<=0? Does it disable omp parallelism? Or does omp then use some default value for the number of threads?"

2024-01-18 21:00 UTC, dkazanc commented on source/libtomo/misc/inpainter.c
> +    if (ncores > 0)
So I've played with it and the conclusion is:
- for ncores <= 0 we've got one core/thread execution only. 
- The rest works as expected.
So no need for this condition to exist really, so I removed it.

2024-01-30 21:30 UTC, carterbox approved these changes
Thanks, @dkazanc!

2024-01-30 21:30 UTC, merged